# Generated by Django 4.2.29 on 2026-04-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='italian', max_length=50),
            preserve_default=False,
        ),
    ]
