# Generated by Django 4.2.29 on 2026-04-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modelmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
