# Generated by Django 4.2.29 on 2026-04-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=4),
        ),
    ]
