# Generated by Django 4.2.30 on 2026-04-12 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_queue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='created_at',
            new_name='joined_at',
        ),
        migrations.AddField(
            model_name='queue',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queue',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
