# Generated by Django 4.2.29 on 2026-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_created_at_queue_joined_at_queue_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['joined_at']},
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('seated', 'Seated'), ('left', 'Left')], default='waiting', max_length=20),
        ),
    ]
