# Generated by Django 4.2.29 on 2026-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_queue_options_alter_queue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_dining_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='occupied_tables',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_tables',
            field=models.IntegerField(default=10),
        ),
    ]
