# Generated by Django 4.2.29 on 2026-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restaurant_lat_restaurant_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
